export enum PERMISSIONS {
  CREATE_USERS = 'CREATE_USERS',
  EDIT_USERS = 'EDIT_USERS',
  DELETE_USERS = 'DELETE_USERS',

  EDIT_COMPANY = 'EDIT_COMPANY',
  CREATE_BRANCH = 'CREATE_BRANCH',
  EDIT_BRANCH = 'EDIT_BRANCH',
  DELETE_BRANCH = 'DELETE_BRANCH',

  CREATE_PURCHASE_ORDER = 'CREATE_PURCHASE_ORDER',
  EDIT_PURCHASE_ORDER = 'EDIT_PURCHASE_ORDER',
  DELETE_PURCHASE_ORDER = 'DELETE_PURCHASE_ORDER',

  CREATE_AUCTION = 'CREATE_AUCTION',
  EDIT_AUCTION = 'EDIT_AUCTION',
  DELETE_AUCTION = 'DELETE_AUCTION',

  CREATE_PRODUCTS_LIST = 'CREATE_PRODUCTS_LIST',
  EDIT_PRODUCTS_LIST = 'EDIT_PRODUCTS_LIST',
  DELETE_PRODUCTS_LIST = 'DELETE_PRODUCTS_LIST',

  CREATE_PRODUCTS_BLACK_LIST = 'CREATE_PRODUCTS_BLACK_LIST',
  EDIT_PRODUCTS_BLACK_LIST = 'EDIT_PRODUCTS_BLACK_LIST',
  DELETE_PRODUCTS_BLACK_LIST = 'DELETE_PRODUCTS_BLACK_LIST',

  CREATE_BRANDS_BLACK_LIST = 'CREATE_BRANDS_BLACK_LIST',
  EDIT_BRANDS_BLACK_LIST = 'EDIT_BRANDS_BLACK_LIST',
  DELETE_BRANDS_BLACK_LIST = 'DELETE_BRANDS_BLACK_LIST',

  CREATE_FAVORITES = 'CREATE_FAVORITES',
  EDIT_FAVORITES = 'EDIT_FAVORITES',
  DELETE_FAVORITES = 'DELETE_FAVORITES',
}
